/**
 * Dashboard 弹框兼容导出。
 *
 * 说明：
 * - 新配置统一维护在 `src/config/project/project.workflow.config.js`。
 * - 本文件保留旧 import 路径，避免一次性改动所有调用方。
 */
export {
  DASHBOARD_OPERATION_TEXT,
  PROJECT_CREATED_TEXT,
  PROJECT_CREATE_FAILED_TEXT,
  PROJECT_BUSY_STATUS_TEXTS,
  PROJECT_CREATING_TEXT,
  PROJECT_DELETE_SCOPE_OPTIONS,
  PROJECT_RUNTIME_TEXT,
  PROJECT_RUNNING_TEXT,
  PROJECT_SETTING_DATABASE_TERMINAL_FIELDS,
  PROJECT_SETTING_NGINX_TERMINAL_FIELDS,
  PROJECT_SETTING_TERMINAL_FIELDS,
  PROJECT_SETTING_TERMINAL_TEXT,
  PROJECT_SETTING_TERMINAL_FACTORY,
  PROJECT_SETTING_TEXT,
  PROJECT_STOPPED_TEXT,
  PROJECT_SYNCING_TEXT,
} from '@/config/project/project.workflow.config'

/**
 * 重新导出项目表单默认值。
 *
 * 来源：
 * - `src/config/project/project.form.defaults.config.js`
 */
export {
  DB_PORT_MAX,
  DB_PORT_MIN,
  DEFAULT_DB_PASSWORD,
  DEFAULT_DB_PORT,
  DEFAULT_DB_USER,
  DEFAULT_ENV_DESCRIPTION,
  DEFAULT_ENV_NAME,
  DEFAULT_ENV_PYTHON_VERSION,
  DEFAULT_SERVER_REMARK,
  DEFAULT_SETTING_REMARK,
  PORT_MAX,
  PORT_MIN,
} from '@/config/project/project.form.defaults.config'
