const allProjectActions = [
  'start_fg',
  'start_bg',
  'deploy_start',
  'stop',
  'setting',
  'detail',
  'log',
  'tools',
  'delete',
]

export const viewPresetsConfig = [
  {
    key: 'full',
    label: '完整视图',
    toolbarSections: ['member-filter', 'status-filter', 'create-button'],
    menus: {
      projects: {
        menuLabel: '项目管理',
        menuHint: '统一管理项目、端口、命令和状态，支持启动、停止、部署、复制、导出等操作。',
        showColumns: [
          'owner',
          'name',
          'description',
          'serverIp',
          'nginxInfo',
          'databaseInfo',
          'runningPort',
          'serviceStatus',
          'projectStatus',
        ],
        showProjectActions: allProjectActions,
        actionsMinWidth: 620,
        actionsLabel: '操作',
        detailFields: [
          'name',
          'owner',
          'serverIp',
          'backendDevPort',
          'backendDeployPort',
          'frontendPort',
          'path',
          'nginxPath',
          'databaseName',
          'status',
          'devCommand',
          'deployCommand',
        ],
        detailDrawerTitle: '项目详情',
        detailDrawerSize: '430px',
        createFields: ['name', 'pythonVersion', 'description', 'path', 'condaName', 'serverIp'],
        createDialogWidth: '760px',
        settingFields: [
          'projectName',
          'entryFilePath',
          'backendDevPort',
          'devCommand',
          'backendDeployPort',
          'deployCommand',
          'frontendPort',
          'remark',
        ],
        copyFields: ['projectName', 'targetServerIp', 'targetDir'],
        exportFields: ['projectName', 'targetDir'],
        sessionFields: ['serverIp', 'alias'],
        settingDialogWidth: '860px',
        copyDialogWidth: '560px',
        exportDialogWidth: '560px',
        sessionDialogWidth: '560px',
        toolDialogTitle: '项目工具',
        toolDialogWidth: '620px',
        toolButtons: ['复制项目', '导出项目', '数据库导出数据', '导出日志文件', '上传文件到项目', '下载项目文件'],
        deleteConfirmTitle: '删除项目',
        deleteConfirmText: '确定删除项目 {name} 吗？此操作不可逆。',
        deleteSuccessText: '项目删除成功',
      },
      users: {
        menuLabel: '用户管理',
        menuHint: '管理账号、密码和角色，支持新增和删除用户。',
        showColumns: ['username', 'password', 'role', 'operator', 'createdAt'],
        actionsMinWidth: 90,
        actionsLabel: '操作',
        createFields: ['username', 'password'],
        createDialogWidth: '460px',
        deleteConfirmTitle: '删除用户确认',
        deleteConfirmText: '确定要删除用户 {name} 吗？',
        deleteSuccessText: '用户 {name} 删除成功',
      },
      envs: {
        menuLabel: '环境管理',
        menuHint: '管理 Conda 环境，查看主包与版本信息。',
        showColumns: ['envName', 'projectName', 'createdAt'],
        actionsMinWidth: 140,
        actionsLabel: '操作',
        createFields: ['name', 'pythonVersion', 'description'],
        createDialogWidth: '520px',
      },
      servers: {
        menuLabel: '服务器管理',
        menuHint: '管理服务器信息与已分配用户（默认包含 root）。',
        showColumns: ['ip', 'rootPassword', 'users', 'remark'],
        actionsMinWidth: 180,
        actionsLabel: '操作',
        createFields: ['ip', 'rootPassword', 'remark'],
        createDialogWidth: '520px',
      },
    },
  },
  {
    key: 'compact',
    label: '紧凑视图',
    toolbarSections: ['member-filter', 'create-button'],
    menus: {
      projects: {
        menuLabel: '项目管理',
        menuHint: '聚焦常用字段与核心操作。',
        showColumns: ['owner', 'name', 'serverIp', 'nginxInfo', 'runningPort', 'serviceStatus', 'projectStatus'],
        showProjectActions: ['start_fg', 'start_bg', 'stop', 'detail', 'log'],
        actionsMinWidth: 420,
        actionsLabel: '操作',
        detailFields: [
          'name',
          'owner',
          'serverIp',
          'frontendPort',
          'backendDevPort',
          'backendDeployPort',
          'databaseName',
          'status',
        ],
        detailDrawerTitle: '项目详情',
        detailDrawerSize: '430px',
        createFields: ['name', 'pythonVersion', 'description', 'path', 'condaName', 'serverIp'],
        createDialogWidth: '760px',
        settingFields: [
          'projectName',
          'entryFilePath',
          'backendDevPort',
          'devCommand',
          'backendDeployPort',
          'deployCommand',
          'frontendPort',
        ],
        copyFields: ['projectName', 'targetDir'],
        exportFields: ['projectName', 'targetDir'],
        sessionFields: ['serverIp', 'alias'],
        settingDialogWidth: '860px',
        copyDialogWidth: '560px',
        exportDialogWidth: '560px',
        sessionDialogWidth: '560px',
        toolDialogTitle: '项目工具',
        toolDialogWidth: '620px',
        toolButtons: ['复制项目', '导出项目', '数据库导出数据', '导出日志文件', '上传文件到项目', '下载项目文件'],
        deleteConfirmTitle: '删除项目',
        deleteConfirmText: '确定删除项目 {name} 吗？此操作不可逆。',
        deleteSuccessText: '项目删除成功',
      },
      users: {
        menuLabel: '用户管理',
        menuHint: '管理账号、密码和角色，支持新增和删除用户。',
        showColumns: ['username', 'password', 'role'],
        actionsMinWidth: 90,
        actionsLabel: '操作',
        createFields: ['username', 'password'],
        createDialogWidth: '460px',
        deleteConfirmTitle: '删除用户确认',
        deleteConfirmText: '确定要删除用户 {name} 吗？',
        deleteSuccessText: '用户 {name} 删除成功',
      },
      envs: {
        menuLabel: '环境管理',
        menuHint: '管理 Conda 环境，查看主包与版本信息。',
        showColumns: ['envName', 'projectName'],
        actionsMinWidth: 140,
        actionsLabel: '操作',
        createFields: ['name', 'pythonVersion', 'description'],
        createDialogWidth: '520px',
      },
      servers: {
        menuLabel: '服务器管理',
        menuHint: '管理服务器信息与已分配用户（默认包含 root）。',
        showColumns: ['ip', 'rootPassword', 'users', 'remark'],
        actionsMinWidth: 180,
        actionsLabel: '操作',
        createFields: ['ip', 'rootPassword', 'remark'],
        createDialogWidth: '520px',
      },
    },
  },
]
